/*
 *<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<    Port_config.h  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 *
 * Author  : Mostafa AboSalama
 *  Layer  : MCAL
 *
 *
 */ 

#ifndef _PORT_CONFIG_H_
#define _PORT_CONFIG_H_

/* PIN DIRECTION */
#define DIO_PIN_OUTPUT	1
#define DIO_PIN_INPUT	0

/* 
	Options :
	
		1- DIO_PIN_OUTPUT	
		2- DIO_PIN_INPUT	
		
*/

#define PORTA_PIN0_DIR				DIO_PIN_INPUT
#define PORTA_PIN1_DIR				DIO_PIN_INPUT
#define PORTA_PIN2_DIR				DIO_PIN_INPUT
#define PORTA_PIN3_DIR				DIO_PIN_INPUT
#define PORTA_PIN4_DIR				DIO_PIN_INPUT
#define PORTA_PIN5_DIR				DIO_PIN_INPUT
#define PORTA_PIN6_DIR				DIO_PIN_INPUT
#define PORTA_PIN7_DIR				DIO_PIN_INPUT
									
#define PORTB_PIN0_DIR				DIO_PIN_INPUT			
#define PORTB_PIN1_DIR				DIO_PIN_INPUT			
#define PORTB_PIN2_DIR				DIO_PIN_INPUT			
#define PORTB_PIN3_DIR				DIO_PIN_INPUT			
#define PORTB_PIN4_DIR				DIO_PIN_INPUT			
#define PORTB_PIN5_DIR				DIO_PIN_INPUT			
#define PORTB_PIN6_DIR				DIO_PIN_INPUT			
#define PORTB_PIN7_DIR				DIO_PIN_INPUT	
									
#define PORTC_PIN0_DIR				DIO_PIN_INPUT
#define PORTC_PIN1_DIR				DIO_PIN_INPUT
#define PORTC_PIN2_DIR				DIO_PIN_INPUT
#define PORTC_PIN3_DIR				DIO_PIN_INPUT			
#define PORTC_PIN4_DIR				DIO_PIN_INPUT			
#define PORTC_PIN5_DIR				DIO_PIN_INPUT			
#define PORTC_PIN6_DIR				DIO_PIN_INPUT			
#define PORTC_PIN7_DIR				DIO_PIN_INPUT	
									
#define PORTD_PIN0_DIR				DIO_PIN_INPUT			
#define PORTD_PIN1_DIR				DIO_PIN_INPUT			
#define PORTD_PIN2_DIR				DIO_PIN_INPUT			
#define PORTD_PIN3_DIR				DIO_PIN_INPUT			
#define PORTD_PIN4_DIR				DIO_PIN_INPUT			
#define PORTD_PIN5_DIR				DIO_PIN_INPUT			
#define PORTD_PIN6_DIR				DIO_PIN_INPUT			
#define PORTD_PIN7_DIR				DIO_PIN_INPUT

		/* PIN VALUES */

/* INPUT Values   */
#define DIO_INPUT_FLOATING 0
#define DIO_INPUT_PULLUP   1

/* OUTPUT Values  */
#define DIO_PIN_HIGH	1
#define DIO_PIN_LOW		0

/*  Options :
			1- DIO_INPUT_FLOATING
			2- DIO_INPUT_PULLUP
			3- DIO_OUTPUT_LOW  
			4- DIO_OUTPUT_HIGH 
*/

#define PORTA_PIN0_INITIAL_VALUE	DIO_INPUT_FLOATING
#define PORTA_PIN1_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN2_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN3_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN4_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN5_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN6_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTA_PIN7_INITIAL_VALUE	DIO_INPUT_FLOATING
									
#define PORTB_PIN0_INITIAL_VALUE	DIO_INPUT_FLOATING
#define PORTB_PIN1_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN2_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN3_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN4_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN5_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN6_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTB_PIN7_INITIAL_VALUE	DIO_INPUT_FLOATING
									
#define PORTC_PIN0_INITIAL_VALUE	DIO_INPUT_FLOATING
#define PORTC_PIN1_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN2_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN3_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN4_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN5_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN6_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTC_PIN7_INITIAL_VALUE	DIO_INPUT_FLOATING
									
#define PORTD_PIN0_INITIAL_VALUE	DIO_INPUT_FLOATING
#define PORTD_PIN1_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN2_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN3_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN4_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN5_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN6_INITIAL_VALUE    DIO_INPUT_FLOATING
#define PORTD_PIN7_INITIAL_VALUE	DIO_INPUT_FLOATING


/* CONCATINATION */
#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)			CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)	(0b##b7##b6##b5##b4##b3##b2##b1##b0)

/* PORTS INITIAL DIRECTION */
#define PORTA_DIR  				CONC(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)
#define PORTB_DIR				CONC(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)
#define PORTC_DIR				CONC(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)
#define PORTD_DIR				CONC(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)

#define PORTA_INITIAL_VALUE		CONC(PORTA_PIN7_INITIAL_VALUE,PORTA_PIN6_INITIAL_VALUE,PORTA_PIN5_INITIAL_VALUE,PORTA_PIN4_INITIAL_VALUE,PORTA_PIN3_INITIAL_VALUE,PORTA_PIN2_INITIAL_VALUE,PORTA_PIN1_INITIAL_VALUE,PORTA_PIN0_INITIAL_VALUE)
#define PORTB_INITIAL_VALUE		CONC(PORTB_PIN7_INITIAL_VALUE,PORTB_PIN6_INITIAL_VALUE,PORTB_PIN5_INITIAL_VALUE,PORTB_PIN4_INITIAL_VALUE,PORTB_PIN3_INITIAL_VALUE,PORTB_PIN2_INITIAL_VALUE,PORTB_PIN1_INITIAL_VALUE,PORTB_PIN0_INITIAL_VALUE)
#define PORTC_INITIAL_VALUE		CONC(PORTC_PIN7_INITIAL_VALUE,PORTC_PIN6_INITIAL_VALUE,PORTC_PIN5_INITIAL_VALUE,PORTC_PIN4_INITIAL_VALUE,PORTC_PIN3_INITIAL_VALUE,PORTC_PIN2_INITIAL_VALUE,PORTC_PIN1_INITIAL_VALUE,PORTC_PIN0_INITIAL_VALUE)
#define PORTD_INITIAL_VALUE		CONC(PORTD_PIN7_INITIAL_VALUE,PORTD_PIN6_INITIAL_VALUE,PORTD_PIN5_INITIAL_VALUE,PORTD_PIN4_INITIAL_VALUE,PORTD_PIN3_INITIAL_VALUE,PORTD_PIN2_INITIAL_VALUE,PORTD_PIN1_INITIAL_VALUE,PORTD_PIN0_INITIAL_VALUE)

#endif /* _PORT_CONFIG_H_ */


